server:
  port: 8083

spring:
  application:
    name: ms-transaction
  datasource:
    url: jdbc:mysql://localhost:3306/banking_system
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

account-service:
  url: http://localhost:8082