server:
  port: 8083

spring:
  application:
    name: ms-transaction
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

account-service:
  url: ${ACCOUNT_SERVICE_URL}